export default [{
        title:'您的性别',
        type:1,
        items:[{
            title:'男',
            check:false,
        },
        {
            title:'女',
            check:false,
        },
        ]
    },
    {
        title:'您的年龄',
        type:1,
        items:[{
            title:'20-30',
            check:false,
        },
        {
            title:'31-40',
            check:false,
        },
        {
            title:'41-50',
            check:false,
        },
        {
            title:'50以上',
            check:false,
        },
        ]
    },
    {
        title:'家庭年收入',
        type:1,
        items:[{
            title:'5万元以下',
            check:false,
        },
        {
            title:'5万—10万元',
            check:false,
        },
        {
            title:'10万元—20万元',
            check:false,
        },
        {
            title:'20万—30万元',
            check:false,
        },
        {
            title:'30万元以上',
            check:false,
        },
        ]
    },
    {
        title:'您是否有过家庭装修的经验（你对家装了解多少）',
        type:1,
        items:[{
            title:'了解，很清楚',
            check:false,
        },
        {
            title:'不太了解',
            check:false,
        },
        {
            title:'完全不懂',
            check:false,
        },
        ]
    },
    {
        title:'您通过什么渠道了解装修',
        type:1,
        items:[{
            title:'电视宣传广告',
            check:false,
        },
        {
            title:'报刊、杂志、户外广告',
            check:false,
        },
        {
            title:'互联网',
            check:false,
        },
        {
            title:'同事或朋友',
            check:false,
        },
        {
            title:'其他',
            check:false,
        },
        ]
    },
    {
        title:'你对于互联网装修，网上找工人APP怎么看',
        type:1,
        items:[{
            title:'不了解，不清楚',
            check:false,
        },
        {
            title:'不相信',
            check:false,
        },
        {
            title:'愿意去了解，如果合适可以借助互联网工具',
            check:false,
        },
        {
            title:'体验过互联网装修',
            check:false,
        },
        ]
    },
    {
        title:'你有网购家装建材类商品的经历吗',
        type:1,
        items:[{
            title:'有',
            check:false,
        },
        {
            title:'没有',
            check:false,
        },
        ]
    },
    {
        title:'你认为装修的利润多少合理？（以10万报价为例）',
        type:1,
        items:[{
            title:'5千以下',
            check:false,
        },
        {
            title:'5千到1万',
            check:false,
        },
        {
            title:'1万到2万5',
            check:false,
        },
        {
            title:'2万5以上',
            check:false,
        },
        ]
    },
    {
        title:'如果要装修，您会找',
        type:1,
        items:[{
            title:'通过宣传资料，找正规大品牌装修公司',
            check:false,
        },
        {
            title:'通过朋友介绍找信得过的装修队',
            check:false,
        },
        {
            title:'找马路游击队',
            check:false,
        },
        {
            title:'多方面比较，选择满意的装修公司',
            check:false,
        },
        {
            title:'互联网渠道',
            check:false,
        },
        ]
    },
    {
        title:'装修前是否会有以下情况',
        type:2,
        items:[{
            title:'我不知道找谁，不知道该相信谁',
            check:false,
        },
        {
            title:'电话骚扰很烦',
            check:false,
        },
        {
            title:'不知道选择什么装修模式好',
            check:false,
        },
        {
            title:'我有明确的计划和值得相信的装修朋友',
            check:false,
        },
        ]
    },
    {
        title:'你还会找给你上次装修房子的人来为你现在的房子装修吗',
        type:1,
        items:[{
            title:'不会',
            check:false,
        },
        {
            title:'会',
            check:false,
        },
        {
            title:'我是第一次装修',
            check:false,
        },
        ]
    },
    {
        title:'在室内装修过程中，您有什么样的感受',
        type:1,
        items:[{
            title:'始终有一点不信任装修人员的心理，怕做不好',
            check:false,
        },
        {
            title:'花费了大量的精力和时间，觉得装修很麻烦',
            check:false,
        },
        {
            title:'装修用了很大一笔费用，但装修成果不尽如人意',
            check:false,
        },
        {
            title:'说是包工包料，还是不省心',
            check:false,
        },
        {
            title:'比较放心，效果也很满意',
            check:false,
        },
        ]
    },
    {
        title:'是否觉得在装修过程中，像装修材料，家居等信息量太少，缺乏选择性',
        type:1,
        items:[{
            title:'是，有时想多找点信息，又苦于没有途径，并且太耗时间',
            check:false,
        },
        {
            title:'否',
            check:false,
        },
        ]
    },
    {
        title:'你有做室内空气质量检测的打算吗',
        type:1,
        items:[{
            title:'有',
            check:false,
        },
        {
            title:'没有',
            check:false,
        },
        ]
    },
    {
        title:'您对以下哪种室内污染物有所了解',
        type:1,
        items:[{
            title:'甲醛',
            check:false,
        },
        {
            title:'苯系物',
            check:false,
        },
        {
            title:'氡气',
            check:false,
        },
        {
            title:'氨气',
            check:false,
        },
        {
            title:'TVOC',
            check:false,
        },
        {
            title:'PM2.5',
            check:false,
        },
        {
            title:'PM10',
            check:false,
        },
        ]
    },
    {
        title:'有一款产品可以帮助你解决有毒有害气体，你愿意花多少钱来治理？（真实有效）',
        type:1,
        items:[{
            title:'20元',
            check:false,
        },
        {
            title:'40元',
            check:false,
        },
        {
            title:'60元',
            check:false,
        },
        {
            title:'100元',
            check:false,
        },
        ]
    },
    {
        title:'您准备或已经投资的装修费用是多少',
        type:1,
        items:[{
            title:'三万以内',
            check:false,
        },
        {
            title:'三万至五万',
            check:false,
        },
        {
            title:'五万至十万',
            check:false,
        },
        {
            title:'十万以上',
            check:false,
        },
        ]
    },
    {
        title:'在装修风格上您更青睐哪一种',
        type:1,
        items:[{
            title:'中式',
            check:false,
        },
        {
            title:'美式',
            check:false,
        },
        {
            title:'欧式',
            check:false,
        },
        {
            title:'现代派',
            check:false,
        },
        {
            title:'没有固定风格',
            check:false,
        },
        ]
    },
    {
        title:'在装修时您是否需要设计师为您出设计方案及图纸',
        type:1,
        items:[{
            title:'是，我觉得很重要',
            check:false,
        },
        {
            title:'否，我觉得不需要',
            check:false,
        },
        {
            title:'有没有设计师都没关系',
            check:false,
        },
        ]
    },
    {
        title:'装修前您最担心什么',
        type:1,
        items:[{
            title:'做到一半，装修的人就无处可寻了',
            check:false,
        },
        {
            title:'没有履行合同',
            check:false,
        },
        {
            title:'工程质量出问题',
            check:false,
        },
        {
            title:'“钓鱼工程”（工程进度之中不停地加价要钱）',
            check:false,
        },
        ]
    },
    {
        title:'您认为装饰公司的报价单应包括哪些内容',
        type:1,
        items:[{
            title:'单纯的价格表',
            check:false,
        },
        {
            title:'价格表附带工艺做法说明',
            check:false,
        },
        {
            title:'价格表附带工艺做法说明及材料等级说明',
            check:false,
        },
        ]
    },
    {
        title:'装修过程中遇到服务纠纷，你会如何解决',
        type:1,
        items:[{
            title:'向消费者协会或有关部分投诉',
            check:false,
        },
        {
            title:'咬碎了，自己吞下去',
            check:false,
        },
        {
            title:'网上发帖或者向周围的朋友倾诉',
            check:false,
        },
        {
            title:'直接找对方理论并扣钱',
            check:false,
        },
        ]
    },
    {
        title:'您希望家居装修是由谁设计的',
        type:1,
        items:[{
            title:'自己',
            check:false,
        },
        {
            title:'专业设计人员',
            check:false,
        },
        {
            title:'装修人员或公司',
            check:false,
        },
        {
            title:'家人共同设计',
            check:false,
        },
        {
            title:'其他',
            check:false,
        },
        ]
    },
    {
        title:'您觉得哪一种装修的模式更好',
        type:1,
        items:[{
            title:'只做设计',
            check:false,
        },
        {
            title:'不包材料包施工',
            check:false,
        },
        {
            title:'材料全包',
            check:false,
        },
        {
            title:'施工包辅材 不包主材',
            check:false,
        },
        {
            title:'整体家装（设计、施工、辅材、主材等）',
            check:false,
        },
        ]
    },
    {
        title:'你遇到过下列哪些装修问题',
        type:2,
        items:[{
            title:'装修合同暗藏陷阱',
            check:false,
        },
        {
            title:'偷工减料，影响装修质量；设计不合理',
            check:false,
        },
        {
            title:'价格有陷阱，多花冤枉钱',
            check:false,
        },
        {
            title:'达不到预期效果',
            check:false,
        },
        {
            title:'不能按时完成，拖延工期',
            check:false,
        },
        {
            title:'装修人员不负责',
            check:false,
        },
        ]
    }


]